import type {Metadata} from "next";
import {ConvexClientProvider} from "@/providers/convex-client-provider"
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";
import {ModalProvider} from "@/providers/modal-provider";
import {LiveBlocksClientProvider} from "@/providers/liveblocks-client-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <LiveBlocksClientProvider>
        <ConvexClientProvider>
            <Toaster/>
            <ModalProvider/>
            {children}
        </ConvexClientProvider>
        </LiveBlocksClientProvider>
        </body>
        </html>
    );
}
